{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helm-example.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "helm-example.labels" . | nindent 4 }}
{{- end -}}
